### ISSUE TITLE
unit_test/cluster_script.py issues

### ISSUE THREAD

**Issue by rgerkin** [russelljjarvis/neuronunit_opt#7]
@russelljjarvis 

`get_neab` was not imported but I added that.  Next error:  

```
Traceback (most recent call last):
  File "cluster_script.py", line 152, in <module>
    test_frame['olf_mit'].insert(0,test_frame['Cerebellum Purkinje cell'][0])
KeyError: 'olf_mit'
```

Does that run for you?  

Also, there is a duplicate `cluster_script.py` in neuronunit/examples.  Can we get rid of one of them?

**Comment by rgerkin** [comment]
Or should both of these files be deleted in favor of the beginner-friendly-intro notebook?

**Comment by russelljjarvis** [comment]
Oh yes, sorry I am experiencing that error too.

The basic idea is that the neuroelectro data for the olfactory mitral cell does not contain a rheobase observation value. My approach was to borrow the rheobase observation value from the Purkinje cell.

It turns out that at some point, I had contracted the proper neuroelectro ontology to `olf_mit`. It's real name is something else.

Sharon, and you have both requested examples of NU-Optimizer usage. Most python repositories have an examples sub-directory, therefore I think the version in unit_test, should be deleted.

**Comment by rgerkin** [comment]
I think it should be in "examples", and then we can have an example_tests.py file in "unit_tests" that runs all the example notebooks to make sure they run.

**Comment by russelljjarvis** [comment]
The better fix, to the olf_mit variable naming problem, would to create a specific test suite for the olfactory bulb cell that doesn't optimize with respect to rheobase. The optimizer should be able to handle being passed in arbitrary test suites now. 

I think it's best for now, to comment out `olf_mit` related code, and then to make specific test suite for that cell lacking Rheobase later.

**Comment by rgerkin** [comment]
Once you have a version that runs to completion for you in unmerged_dev, I will run it against my merge.

**Comment by russelljjarvis** [comment]
I think the current version will.
